#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9
TOTAL_MINUTES=690 # About 3.5 hours hands-on plus one passive 8-hour observation.

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
RUN_DATE="${RUN_DATE:-$(date +%F)}"
AUDIT_DIR="${AUDIT_DIR:-$REPO_ROOT/docs/audits/${RUN_DATE}-real-device-live-activity}"
EVIDENCE_DIR="${EVIDENCE_DIR:-$AUDIT_DIR/evidence}"
RESULT_FILE="${RESULT_FILE:-$AUDIT_DIR/acceptance-record.md}"
ENV_FILE="${ENV_FILE:-$AUDIT_DIR/.wizard.env}"
COMPLETED_FILE="$AUDIT_DIR/.completed-cases"
XCODE_PROJECT="$REPO_ROOT/IslandNotes/IslandNotes.xcodeproj"
DEVICE_UDID="${DEVICE_UDID:-00008140-0010654C0E62801C}"
APP_BUNDLE_ID="com.steve.IslandNotes"

mkdir -p "$EVIDENCE_DIR"
touch "$COMPLETED_FILE"

md_escape() {
  local value="$1"
  value=${value//$'\n'/<br>}
  value=${value//|/\\|}
  printf '%s' "$value"
}

ask_status() {
  local output_var="$1" reply=""
  while true; do
    printf '  %sResult%s [p=pass / f=fail / b=blocked / s=skip]: ' "$BOLD" "$RESET"
    read -r reply || true
    case "$reply" in
      p|P|pass|PASS) printf -v "$output_var" '%s' "pass"; return ;;
      f|F|fail|FAIL) printf -v "$output_var" '%s' "fail"; return ;;
      b|B|blocked|BLOCKED) printf -v "$output_var" '%s' "blocked"; return ;;
      s|S|skip|SKIP) printf -v "$output_var" '%s' "skip"; return ;;
      *) warn "enter p, f, b, or s" ;;
    esac
  done
}

ensure_report() {
  [[ -f "$RESULT_FILE" ]] && return 0
  {
    printf '# Island Notes 真机发布验收记录\n\n'
    printf '> 来源：`docs/verification/real-device-live-activity-checklist.md`  '
    printf '\n> 真机结果不得由 Preview 或 Simulator 代替。\n\n'
    printf '## 自动预检\n\n'
    printf -- '- Release 真机构建：pass（2026-08-10，`xcodebuild`，BUILD SUCCEEDED）\n'
    printf -- '- 安装：pass（1.0 (1) 已安装到 iPhone 16 Pro）\n'
    printf -- '- 自动启动：blocked（设备锁定，SpringBoard 拒绝远程启动；不计为 App 缺陷）\n'
    printf -- '- 已连接真机：iPhone 16 Pro (iPhone17,1)，iOS 26.5.2\n'
    printf -- '- 第二种灵动岛宽度真机：未连接，发布判定前必须补证或记录偏差。\n\n'
    printf '## 测试批次\n\n'
    printf '| 字段 | 值 |\n|---|---|\n'
    printf '| App 构建/版本 | 1.0 (1) · Release |\n'
    printf '| 测试日期 | %s |\n' "$(md_escape "${TEST_DATE:-$RUN_DATE}")"
    printf '| 测试人 | %s |\n' "$(md_escape "${TESTER:-未填写}")"
    printf '| 主设备 | %s |\n' "$(md_escape "${PRIMARY_DEVICE:-iPhone 16 Pro (iPhone17,1), iOS 26.5.2}")"
    printf '| 第二宽度设备 | %s |\n' "$(md_escape "${SECONDARY_DEVICE:-未提供}")"
    printf '| 语言/地区/外观/字体 | %s |\n\n' "$(md_escape "${SYSTEM_CONFIGURATION:-未填写}")"
    printf '## 逐项结果\n\n'
    printf '| 时间 | ID | 检查项 | 结果 | 备注 / 证据 |\n'
    printf '|---|---|---|---|---|\n'
  } > "$RESULT_FILE"
}

record_case() {
  local id="$1" description="$2" status="" notes=""
  if grep -Fxq "$id" "$COMPLETED_FILE"; then
    note "$id already recorded — skipped (remove it from $COMPLETED_FILE to retest)"
    return 0
  fi
  printf '\n'
  say "$id · $description"
  ask_status status
  printf '  %sNotes / evidence path%s [optional]: ' "$BOLD" "$RESET"
  read -r notes || true
  printf '| %s | %s | %s | %s | %s |\n' \
    "$(date '+%F %T %z')" \
    "$(md_escape "$id")" \
    "$(md_escape "$description")" \
    "$(md_escape "$status")" \
    "$(md_escape "$notes")" >> "$RESULT_FILE"
  printf '%s\n' "$id" >> "$COMPLETED_FILE"
  printf '  %s✓ recorded%s %s → %s\n' "$GREEN" "$RESET" "$id" "$RESULT_FILE"
}

record_auto() {
  local id="$1" description="$2" status="$3" notes="$4"
  grep -Fxq "$id" "$COMPLETED_FILE" && return 0
  printf '| %s | %s | %s | %s | %s |\n' \
    "$(date '+%F %T %z')" \
    "$(md_escape "$id")" \
    "$(md_escape "$description")" \
    "$(md_escape "$status")" \
    "$(md_escape "$notes")" >> "$RESULT_FILE"
  printf '%s\n' "$id" >> "$COMPLETED_FILE"
}

copy_sample() {
  local glyph="$1" count="$2" label="$3"
  if command -v python3 >/dev/null 2>&1 && command -v pbcopy >/dev/null 2>&1; then
    python3 -c 'import sys; print(sys.argv[1] * int(sys.argv[2]), end="")' \
      "$glyph" "$count" | pbcopy
    printf '  %s✓ copied%s %s to the Mac clipboard\n' "$GREEN" "$RESET" "$label"
  else
    warn "could not copy sample automatically; generate $count repetitions of: $glyph"
  fi
}

open_xcode_project() {
  if command -v open >/dev/null 2>&1; then
    open "$XCODE_PROJECT" >/dev/null 2>&1 || true
  fi
}

launch_stale_deep_link() {
  local url="islandnotes://workbench?noteID=00000000-0000-0000-0000-000000000000"
  if command -v xcrun >/dev/null 2>&1; then
    if xcrun devicectl device process launch \
      --device "$DEVICE_UDID" \
      --payload-url "$url" \
      --terminate-existing \
      "$APP_BUNDLE_ID"; then
      return 0
    fi
  fi
  warn "automatic deep-link launch failed; run after unlocking:"
  note "xcrun devicectl device process launch --device $DEVICE_UDID --payload-url '$url' --terminate-existing $APP_BUNDLE_ID"
  return 1
}

acceptance_finish() {
  local passed failed blocked skipped
  passed=$(awk -F'|' '$5 ~ /^[[:space:]]*pass[[:space:]]*$/ {n++} END {print n+0}' "$RESULT_FILE")
  failed=$(awk -F'|' '$5 ~ /^[[:space:]]*fail[[:space:]]*$/ {n++} END {print n+0}' "$RESULT_FILE")
  blocked=$(awk -F'|' '$5 ~ /^[[:space:]]*blocked[[:space:]]*$/ {n++} END {print n+0}' "$RESULT_FILE")
  skipped=$(awk -F'|' '$5 ~ /^[[:space:]]*skip[[:space:]]*$/ {n++} END {print n+0}' "$RESULT_FILE")
  _clear
  printf '\n%s%s  Island Notes acceptance checkpoint%s\n\n' "$BOLD" "$GREEN" "$RESET"
  say "pass=$passed · fail=$failed · blocked=$blocked · skip=$skipped"
  say "report: $RESULT_FILE"
  say "evidence: $EVIDENCE_DIR"
  if (( failed > 0 || blocked > 0 || skipped > 0 )); then
    warn "release gate is NOT clear; resolve every fail/blocked/skip or document a tightened product commitment"
  else
    say "All recorded checks passed. Review evidence completeness before recording GO."
  fi
  printf '\n'
}

banner "Island Notes · 真机发布验收"

stage "批次、安装与首次授权" 15
say "先建立可审计批次。当前 Release 构建已通过并安装；设备锁定导致自动启动被拒。"
open_xcode_project
step "解锁 iPhone；在 Xcode 顶栏选择 iPhone 16 Pro，Product → Run，确认出现 Island Notes 工作台。"
ask TESTER "测试人："
TEST_DATE="$RUN_DATE"
PRIMARY_DEVICE="iPhone 16 Pro (iPhone17,1), iOS 26.5.2"
ask SECONDARY_DEVICE "第二种灵动岛宽度真机（机型 + iOS；没有则填 unavailable）："
ask SYSTEM_CONFIGURATION "系统语言、地区、外观与字体大小："
write_env TESTER "$TESTER"
write_env TEST_DATE "$TEST_DATE"
write_env PRIMARY_DEVICE "$PRIMARY_DEVICE"
write_env SECONDARY_DEVICE "$SECONDARY_DEVICE"
write_env SYSTEM_CONFIGURATION "$SYSTEM_CONFIGURATION"
ensure_report
record_auto "A00" "Release 真机构建并安装到主设备" "pass" "xcodebuild BUILD SUCCEEDED；devicectl install succeeded"
record_case "A01" "真机可启动，工作台显示 1.0 (1) 当前构建"
warn "首次授权/拒绝测试可能需要删除 App；这会删除 Island Notes 的全部本机便签。"
if confirm "本机便签已不需要或已另行记录，可以删除 App 后由 Xcode 重装？"; then
  step "在 iPhone 长按 Island Notes → Remove App → Delete App；随后回 Xcode 再次 Product → Run。"
  step "输入非空正文、点 Done，再点 Go Live；记录系统是否出现提示、提示文案和拒绝后的 App 状态。"
else
  warn "不要删除 App；把首次授权/拒绝项记录为 blocked，并说明保留本机数据。"
fi
record_case "P01" "首次 Go Live 的系统提示与拒绝路径符合实际系统行为；拒绝不丢正文且不虚报 Live"

stage "Core presentation 与全部入口" 30
say "准备一条包含长文、换行、Emoji 和 '- ' 圆点行的正文，Done 后点 Go Live。"
step "观察 compact leading/trailing：只应有图标和状态点，不出现正文。"
record_case "P02" "compact leading/trailing 只显示便签标记与状态，不泄露正文"
step "启动另一个 App 的 Live Activity（例如计时器/体育比分），让系统把 Island Notes 放入 minimal。"
record_case "P03" "minimal 只显示单色便签标记，不泄露正文"
step "长按灵动岛进入 expanded；检查最新已保存正文、换行、Emoji、圆点行和安全截断，不应滚动。"
record_case "P04" "expanded 展示最新 ContentState，长文、换行与 Emoji 安全截断且不滚动"
step "锁屏，核对 Lock Screen 与 expanded 的正文数据一致。"
record_case "P05" "Lock Screen 与 expanded 使用同一最新 ContentState 正文"
step "分别轻点 compact leading、compact trailing、minimal、expanded 和 Lock Screen；每次都应打开当前工作台。"
record_case "P06" "compact、minimal、expanded、Lock Screen 的每个入口都返回当前工作台"
step "保持设备解锁并停在主屏幕；向导将发送一个带失效 noteID 的 deep link。"
pause "Press Enter to send the stale deep link."
launch_stale_deep_link || true
record_case "P07" "失效 noteID 只打开当前工作台并对账，不恢复、交换或重新挂起旧便签"

stage "request、update、end 与对账" 30
step "确保状态为 Not Live，输入短正文并 Done；点 Go Live，确认状态变 Live 且系统出现活动。"
record_case "L01" "真实 ActivityKit request 成功"
step "快速重复点 Go Live；若按钮已变 Live，不要把停止动作当重复 request。确认系统始终只有一条 Island Notes 活动。"
record_case "L02" "重复启动操作不会创建第二条 Island Notes Live Activity"
step "点正文进入编辑，修改为明显不同内容，点 Done，等待至少 1 秒后核对 expanded 与锁屏。"
record_case "L03" "同一 Activity 的真实 update 成功，且展示最新已保存正文"
step "点 Live 停止；灵动岛应立即移除，App 变 Not Live，正文仍保留。"
record_case "L04" "真实 ActivityKit end 成功，且不丢本机正文"
step "再次 Go Live；在锁屏活动上使用系统提供的移除/清除动作，回到 App 前台。"
record_case "L05" "手动移除活动后，App 回前台对账为 Not Live"
note "需要枚举证据时：Xcode 暂停进程，在 Debug Console 执行："
note "po Activity<IslandNoteActivityAttributes>.activities.map { ($0.id, $0.activityState) }"

stage "后台、终止、崩溃、强杀、重启与隔离" 60
say "每个子场景先 Go Live，并记录时间、系统展示、重开后枚举及 deep link。"
step "后台：按 Home/上滑回主屏，分别检查灵动岛和锁屏，再点活动返回。"
record_case "L06" "App 在后台时的系统展示、deep link 与重开枚举结果已记录"
step "正常终止没有稳定的人工作法；若本批次由系统正常回收进程则记录，否则 blocked 并写观察窗口。"
record_case "L07" "App 正常终止后的系统展示与重开枚举结果已记录"
step "崩溃：从 Xcode 运行并 Go Live；暂停进程，在 Debug Console 执行 process signal SIGABRT。"
record_case "L08" "App 崩溃后的系统展示与重开枚举结果已记录"
step "用户强杀：Go Live 后回主屏，打开 App Switcher，把 Island Notes 卡片上滑移除。"
record_case "L09" "用户强杀后的系统展示与重开枚举结果已记录"
warn "设备重启会中断当前使用。"
if confirm "现在执行重启测试？"; then
  step "Go Live，先截图并记录时间；关闭并重新开启 iPhone。"
  step "开机后先观察灵动岛/锁屏，再点 deep link；最后从 Xcode 查看 Activity.activities 枚举。"
else
  warn "把重启项记为 blocked，并安排独立窗口。"
fi
record_case "L10" "设备重启前后系统展示、Activity.activities 枚举和 deep link 行为已记录"
step "启动另一个 App 的 Live Activity；反复 Go Live、update、end Island Notes，确认对方活动不变。"
record_case "L11" "存在其他 App Live Activities 时，本 App 不误结束或修改它们"

stage "设置、锁屏、隐私与辅助功能" 55
step "设置 → Apps → Island Notes → Live Activities（路径以系统实际显示为准）：关闭后回 App 尝试 Go Live。"
record_case "S01" "禁用 Live Activities 后启动失败，不丢正文、不虚报 Live"
step "重新启用 Live Activities；回 App 核对没有自动续挂，再由用户手动点 Go Live。"
record_case "S02" "重新启用后可再次 Go Live，但不会自动续挂"
step "组合测试锁定/解锁，以及 Face ID 与密码 → Allow Access When Locked → Live Activities 的允许/禁止。"
record_case "S03" "锁定/解锁与允许/禁止锁屏访问的组合行为已记录"
step "若设备支持：显示与亮度 → Always On Display，分别开/关并截图；不支持则 skip 并注明机型。"
record_case "S04" "Always-On 开/关组合的实际显示已记录（设备支持时）"
step "记录系统在锁屏未认证、已认证和隐私设置组合下的 redaction；产品不承诺绕过系统。"
record_case "S05" "系统隐私/redaction 行为已记录，未声称绕过系统策略"
step "逐项切换浅色、深色、提高对比度、Reduce Motion；检查 Live/Not Live 与关键动作不只依赖颜色或动画。"
record_case "S06" "浅色、深色、提高对比度、Reduce Motion 下状态表达可辨识"
step "开启 VoiceOver，按顺序探索编辑器、字符进度、More → Note Library、Move to Note Library、Go Live、Delete Note。"
record_case "S07" "VoiceOver 可读出编辑器、字符进度、库入口、三项动作及 disabled 原因"
step "文字大小调到最大 Accessibility；在工作台、Note Library 与关键动作间滚动，检查触控目标至少 44 pt。"
record_case "S08" "最大 Dynamic Type 下工作台、库与关键动作可滚动到达，触控目标不小于 44 pt"

stage "240 字与 4 KB 边界" 45
say "以下编码大小按生产 Codable JSON 结构计算：attributes 49 bytes，request/update 使用同一上限。"
copy_sample "中" 240 "240 Chinese characters (792 bytes total)"
step "在 Not Live 状态粘贴、Done、Go Live；记录 request；再编辑一个字符后 Done，记录 update。"
record_case "B01" "240 个中文字符：request/update 编码大小、系统结果和 App 反馈已记录（基准 792 bytes）"
copy_sample "a" 240 "240 ASCII characters (312 bytes total)"
step "重复 request 与 update 流程。"
record_case "B02" "240 个 ASCII 字符：request/update 编码大小、系统结果和 App 反馈已记录（基准 312 bytes）"
copy_sample "😀" 240 "240 simple Emoji (1032 bytes total)"
step "重复 request 与 update 流程。"
record_case "B03" "240 个简单 Emoji：request/update 编码大小、系统结果和 App 反馈已记录（基准 1032 bytes）"
copy_sample "👨🏽‍👩🏾‍👧🏿‍👦🏻" 240 "240 complex graphemes (9912 bytes total)"
step "Not Live 时粘贴并 Done；正文应保存。点 Go Live：应被 4096-byte 本地校验阻止并保持 Not Live。"
record_case "B04" "240 个复杂组合字素/家庭 Emoji/变体选择符：request/update 编码大小、系统结果和 App 反馈已记录（基准 9912 bytes）"
record_case "B05" "超过 4 KB 的极端 Unicode request 被本地校验阻止；正文仍保存且不虚报 Live"
copy_sample "a" 240 "a valid 240-character starter"
step "先粘贴有效样本并 Go Live；再把正文改为 240 个复杂组合字素，Done 后等待至少 1 秒。"
copy_sample "👨🏽‍👩🏾‍👧🏿‍👦🏻" 240 "the over-4-KB update sample"
step "粘贴复杂样本并 Done；本机正文应保存，Activity 仍存在且显示旧内容，并出现 Live may not be up to date."
record_case "B06" "已 Live 时 update 超过 4 KB：本机正文保存、实际活动保持、显示可能未同步反馈"

stage "启动 8 小时生命周期观察" 480
say "这是系统硬时限的真实观察，不能用等待命令、Preview 或 Simulator 替代。"
step "恢复默认字体与期望外观，创建一条带明确开始时间的短便签并 Go Live。"
ask OBSERVATION_START "记录开始时间（含时区，例如 2026-08-10 09:00 +0800）："
write_env OBSERVATION_START "$OBSERVATION_START"
step "立即保存 compact、expanded、Lock Screen 截图；随后每小时记录灵动岛与锁屏状态。"
record_case "T00" "8 小时生命周期观察已启动并保存起始证据"
printf '\n  %sPause required by wizard skill:%s real elapsed time must pass.\n' "$YELLOW" "$RESET"
say "现在按 Ctrl-C 结束。8 小时后用同一命令复跑；已记录项目会自动跳过。"
if ! confirm "8 小时已经真实过去，现在继续收尾？"; then
  acceptance_finish
  exit 0
fi

stage "收尾 8 小时与锁屏残留" 15
ask OBSERVATION_END "记录系统从灵动岛结束的时间："
ask LOCKSCREEN_REMOVAL "记录锁屏尾部残留消失时间（或仍在）："
write_env OBSERVATION_END "$OBSERVATION_END"
write_env LOCKSCREEN_REMOVAL "$LOCKSCREEN_REMOVAL"
record_case "T01" "完整运行 8 小时，系统结束时间与 Lock Screen 最多约 4 小时尾部残留已记录"
step "把逐小时记录、强杀、重启、禁用/重开 Live Activities 的时间线放入 evidence/。"
record_case "E01" "8 小时、强杀、重启、禁用/重开的时间线证据完整"

stage "证据核对与发布判定" 10
say "证据目录：$EVIDENCE_DIR"
if command -v open >/dev/null 2>&1; then open "$EVIDENCE_DIR" >/dev/null 2>&1 || true; fi
step "核对 compact、minimal、expanded、Lock Screen、最大字体、深色、隐私组合截图均来自真机。"
record_case "E02" "已附 compact、minimal、expanded、Lock Screen、最大字体、深色与隐私组合真机截图"
record_case "E03" "未把 Preview 或 Simulator 截图标记成真机证据"
record_case "E04" "两种设备宽度必测项全部通过；或每个偏差均有复现步骤、系统版本和承诺收紧结论"
ask RELEASE_DECISION "最终判定（GO / NO-GO / CONDITIONAL）："
ask RELEASE_RATIONALE "判定理由与未关闭偏差："
write_env RELEASE_DECISION "$RELEASE_DECISION"
write_env RELEASE_RATIONALE "$RELEASE_RATIONALE"
{
  printf '\n## 发布判定\n\n'
  printf -- '- 决定：%s\n' "$(md_escape "$RELEASE_DECISION")"
  printf -- '- 理由：%s\n' "$(md_escape "$RELEASE_RATIONALE")"
  printf -- '- 记录时间：%s\n' "$(date '+%F %T %z')"
} >> "$RESULT_FILE"

acceptance_finish
